[package]
name = "lexicons"

license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]

[build-dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
fancy-regex = "0.11.0"
once_cell = "1.17.1"

